name: Run Python Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Set up Python
      #  uses: actions/setup-python@v5
       # with:
       #   python-version: '3.14'

      - name: Activate virtual environment and install dependencies
        shell: bash
        run: |
          source .venv\Scripts\activate 
          #pip install -r requirements.txt

      - name: Run pipeline
        shell: bash
        run: |
          source .venv\Scripts\activate 
          python pipeline.py
