name: Run Python Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ativar ambiente virtual
        shell: cmd
        run: |
          .\.venv\Scripts\activate.bat

      - name: Executar pipeline
        shell: cmd
        run: |
          .\.venv\Scripts\activate.bat
          python pipeline.py
