name: Run Python Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup virtual environment
        shell: powershell
        run: |
          $venvPath = ".\.venv"
          $activateScript = "$venvPath\Scripts\Activate.ps1"

          if (-Not (Test-Path "$activateScript")) {
              Write-Output "Virtual environment not found. Creating it..."
              python -m venv $venvPath
              & "$activateScript"
              pip install --upgrade pip
              pip install -r requirements.txt
          } else {
              Write-Output "Virtual environment found. Skipping creation."
          }

      - name: Run pipeline
        shell: powershell
        run: |
          .\.venv\Scripts\Activate.ps1
          python pipeline.py
