name: Run Python Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Activate virtual environment and install dependencies
        shell: powershell
        run: |
          .\.venv\Scripts\Activate.ps1
          #pip install -r requirements.txt

      - name: Run pipeline
        shell: powershell
        run: |
          .\.venv\Scripts\Activate.ps1
          python pipeline.py